/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AeroportoDao;
import controller.AviaoDao;
import controller.PassageiroDao;
import controller.PassageiroVooDao;
import controller.TripulacaoDao;
import controller.TripulanteDao;
import controller.VooDao;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Aeroporto;
import model.Aviao;
import model.Passageiro;
import model.SmartForTwo;
import model.Tripulante;
import model.Voo;

/**
 *
 * @author renilson
 */
public class TelaVoo extends javax.swing.JFrame {

    private ArrayList<Passageiro> passageiros = new ArrayList<>();
    private ArrayList<Aviao> avioes = new ArrayList<>();
    private ArrayList<Tripulante> tripulantes = new ArrayList<>();
    private ArrayList<Aeroporto> aeroportos = new ArrayList<>();
    private Voo voo;
    private DefaultListModel model;

    /**
     * Creates new form TelaVoo
     */
    public TelaVoo() {
        initComponents();
        inicializaComboBox();
    }

    public TelaVoo(Voo v) {
        initComponents();
        inicializaComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblOrigem = new javax.swing.JLabel();
        cbxOrigem = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxDestino = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxAviao = new javax.swing.JComboBox<>();
        ftxData = new javax.swing.JFormattedTextField();
        ftxHora = new javax.swing.JFormattedTextField();
        bttSalvar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbxPiloto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbxOficial1 = new javax.swing.JComboBox<>();
        cbxOficial2 = new javax.swing.JComboBox<>();
        cbxChefe = new javax.swing.JComboBox<>();
        cbxComissaria1 = new javax.swing.JComboBox<>();
        cbxComissaria2 = new javax.swing.JComboBox<>();
        bttAddTripulante = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        bttInserir = new javax.swing.JButton();
        bttRemover = new javax.swing.JButton();
        cbxPassageiro = new javax.swing.JComboBox<>();
        txtPassageiro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPassageiros = new javax.swing.JList<>();
        bttCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblId.setText("ID:");

        txtId.setEditable(false);

        lblData.setText("Data:");

        lblHora.setText("Hora:");

        lblOrigem.setText("Origem:");

        jLabel5.setText("Destino:");

        jLabel6.setText("Avião:");

        try {
            ftxData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bttSalvar.setText("Salvar");
        bttSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblData)
                                    .addComponent(lblId))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ftxData, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(lblHora)
                                        .addGap(18, 18, 18)
                                        .addComponent(ftxHora, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(lblOrigem))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxOrigem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAviao, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(bttSalvar)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(ftxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHora)
                    .addComponent(ftxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigem)
                    .addComponent(cbxOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAviao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(57, 57, 57)
                .addComponent(bttSalvar)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Dados Gerais", jPanel2);

        jLabel8.setText("Piloto:");

        jLabel9.setText("Oficial 1:");

        jLabel10.setText("Oficial 2:");

        jLabel11.setText("Chefe de Serviço:");

        jLabel12.setText("Comissário(a) 1:");

        jLabel13.setText("Comissário(a) 2:");

        bttAddTripulante.setText("Cadastrar Tripulante");
        bttAddTripulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddTripulanteActionPerformed(evt);
            }
        });

        jButton1.setText("Gerar Mapeamento SmartFortwo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bttAddTripulante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxOficial2, 0, 310, Short.MAX_VALUE)
                                    .addComponent(cbxOficial1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxComissaria1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxComissaria2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(22, 22, 22)
                                    .addComponent(cbxPiloto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxChefe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(73, 73, 73))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxOficial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbxOficial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbxChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbxComissaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxComissaria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bttAddTripulante))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Tripulação", jPanel3);

        jLabel14.setText("Passageiro:");

        bttInserir.setText("Inserir");
        bttInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttInserirActionPerformed(evt);
            }
        });

        bttRemover.setText("Remover passageiro");
        bttRemover.setEnabled(false);
        bttRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRemoverActionPerformed(evt);
            }
        });

        txtPassageiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassageiroKeyReleased(evt);
            }
        });

        listPassageiros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPassageirosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listPassageiros);

        bttCadastrar.setText("Cadastrar");
        bttCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(bttRemover))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtPassageiro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bttCadastrar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(169, 169, 169)
                            .addComponent(bttInserir))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cbxPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttCadastrar))
                .addGap(29, 29, 29)
                .addComponent(cbxPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(bttInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttRemover)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Passageiros", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(466, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInserirActionPerformed
        String pas = cbxPassageiro.getSelectedItem().toString();
        if (!pas.isEmpty()) {
            passageiros.add(new PassageiroDao().buscarPassageiro(Integer.parseInt(pas.substring(0, pas.indexOf(" ")))));
        }
        this.carregarLista();
    }//GEN-LAST:event_bttInserirActionPerformed

    private void bttSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSalvarActionPerformed
        voo = new Voo();
        String data = ftxData.getText();
        String hora = ftxHora.getText();
        String origem = cbxOrigem.getSelectedItem().toString();
        String destino = cbxDestino.getSelectedItem().toString();
        String aviao = cbxAviao.getSelectedItem().toString();

        if (!origem.isEmpty()
                && !destino.isEmpty()
                && !aviao.isEmpty()
                && data.length() == 10 && hora.length() == 5) {

            voo.setData(data);
            voo.setHora(hora);
            voo.setOrigem(aeroportos.get(cbxOrigem.getSelectedIndex()));
            voo.setDestino(aeroportos.get(cbxDestino.getSelectedIndex()));
            voo.setAviao(avioes.get(cbxAviao.getSelectedIndex()));

            new VooDao().inserirVoo(voo);
            Integer idVoo = new VooDao().buscarVoo(voo);
            
            new TripulacaoDao().inserirTripulacao(tripulantes, idVoo);
            new PassageiroVooDao().inserirPassageiro(passageiros, idVoo);
        }
    }//GEN-LAST:event_bttSalvarActionPerformed

    private void listPassageirosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPassageirosMouseClicked
        bttRemover.setEnabled(true);
    }//GEN-LAST:event_listPassageirosMouseClicked

    private void bttRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRemoverActionPerformed
        model = (DefaultListModel) listPassageiros.getModel();
        model.removeElement(listPassageiros.getSelectedIndex());
        passageiros.remove(listPassageiros.getSelectedIndex());
        this.carregarLista();
    }//GEN-LAST:event_bttRemoverActionPerformed

    private void bttCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarActionPerformed
        new TelaPassageiro().setVisible(true);
    }//GEN-LAST:event_bttCadastrarActionPerformed

    private void bttAddTripulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddTripulanteActionPerformed
        new TelaTripulante().setVisible(true);
    }//GEN-LAST:event_bttAddTripulanteActionPerformed

    private void txtPassageiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassageiroKeyReleased
        cbxPassageiro.removeAllItems();
        ArrayList<Passageiro> buscaPassageiros = new PassageiroDao().buscarPassageiroByString(txtPassageiro.getText());
        for (Passageiro p : buscaPassageiros) {
            cbxPassageiro.addItem(p.toString());
        }
    }//GEN-LAST:event_txtPassageiroKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Tripulante> t = new ArrayList<>();
        System.out.println(cbxPiloto.getSelectedItem()
                .toString().substring(0,
                        cbxPiloto.getSelectedItem()
                                .toString().indexOf(" ")));
        t.add(new TripulanteDao().buscarTripulanteById(Integer.parseInt(cbxPiloto.getSelectedItem()
                .toString().substring(0,
                        cbxPiloto.getSelectedItem()
                                .toString().indexOf(" ")))));
        t.add(new TripulanteDao().buscarTripulanteById(Integer.parseInt(cbxOficial1.getSelectedItem()
                .toString().substring(0,
                        cbxOficial1.getSelectedItem()
                                .toString().indexOf(" ")))));
        t.add(new TripulanteDao().buscarTripulanteById(Integer.parseInt(cbxOficial2.getSelectedItem()
                .toString().substring(0,
                        cbxOficial2.getSelectedItem()
                                .toString().indexOf(" ")))));
        t.add(new TripulanteDao().buscarTripulanteById(Integer.parseInt(cbxChefe.getSelectedItem()
                .toString().substring(0,
                        cbxChefe.getSelectedItem()
                                .toString().indexOf(" ")))));
        t.add(new TripulanteDao().buscarTripulanteById(Integer.parseInt(cbxComissaria1.getSelectedItem()
                .toString().substring(0,
                        cbxComissaria1.getSelectedItem()
                                .toString().indexOf(" ")))));
        t.add(new TripulanteDao().buscarTripulanteById(Integer.parseInt(cbxComissaria2.getSelectedItem()
                .toString().substring(0,
                        cbxComissaria2.getSelectedItem()
                                .toString().indexOf(" ")))));
        SmartForTwo sft = new SmartForTwo();
        JOptionPane.showMessageDialog(this, sft.transportar(t));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carregarLista() {
        model = new DefaultListModel();
        for (Passageiro p : passageiros) {
            model.addElement(p.toString());
        }
        listPassageiros.setModel(model);
    }

    private void inicializaComboBox() {
        tripulantes = new TripulanteDao().listarTripulantes();
        for (Tripulante t : tripulantes) {
            if (t.getCargo().getDescricao().equals("Piloto")) {
                cbxPiloto.addItem(t.toString());
            } else if (t.getCargo().getDescricao().equals("Oficial")) {
                cbxOficial1.addItem(t.toString());
                cbxOficial2.addItem(t.toString());
            } else if (t.getCargo().getDescricao().equals("Chefe de Serviço")) {
                cbxChefe.addItem(t.toString());
            } else if (t.getCargo().getDescricao().equals("Comissário(a)")) {
                cbxComissaria1.addItem(t.toString());
                cbxComissaria2.addItem(t.toString());
            }
        }

        avioes = new AviaoDao().listarAviao();
        for (Aviao a : avioes) {
            cbxAviao.addItem(a.toString());
        }

        aeroportos = new AeroportoDao().listarAeroporto();
        for (Aeroporto ae : aeroportos) {
            cbxOrigem.addItem(ae.toString());
            cbxDestino.addItem(ae.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVoo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAddTripulante;
    private javax.swing.JButton bttCadastrar;
    private javax.swing.JButton bttInserir;
    private javax.swing.JButton bttRemover;
    private javax.swing.JButton bttSalvar;
    private javax.swing.JComboBox<String> cbxAviao;
    private javax.swing.JComboBox<String> cbxChefe;
    private javax.swing.JComboBox<String> cbxComissaria1;
    private javax.swing.JComboBox<String> cbxComissaria2;
    private javax.swing.JComboBox<String> cbxDestino;
    private javax.swing.JComboBox<String> cbxOficial1;
    private javax.swing.JComboBox<String> cbxOficial2;
    private javax.swing.JComboBox<String> cbxOrigem;
    private javax.swing.JComboBox<String> cbxPassageiro;
    private javax.swing.JComboBox<String> cbxPiloto;
    private javax.swing.JFormattedTextField ftxData;
    private javax.swing.JFormattedTextField ftxHora;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JList<String> listPassageiros;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPassageiro;
    // End of variables declaration//GEN-END:variables
}
