/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


/**
 *
 * @author renilson
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        mniCadVoo = new javax.swing.JMenuItem();
        mniCadAviao = new javax.swing.JMenuItem();
        mniCadPassageiro = new javax.swing.JMenuItem();
        mniCadTripulante = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        mniConVoo = new javax.swing.JMenuItem();
        mniConAviao = new javax.swing.JMenuItem();
        mniConPassageiro = new javax.swing.JMenuItem();
        mniConTripulante = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CodeIT Airlines");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnCadastros.setText("Cadastros");

        mniCadVoo.setText("Voo");
        mniCadVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadVooActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadVoo);

        mniCadAviao.setText("Avião");
        mniCadAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadAviaoActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadAviao);

        mniCadPassageiro.setText("Passageiro");
        mniCadPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadPassageiroActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadPassageiro);

        mniCadTripulante.setText("Tripulante");
        mniCadTripulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadTripulanteActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadTripulante);

        jMenuBar1.add(mnCadastros);

        mnConsultas.setText("Consultas");

        mniConVoo.setText("Voo");
        mniConVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConVooActionPerformed(evt);
            }
        });
        mnConsultas.add(mniConVoo);

        mniConAviao.setText("Avião");
        mniConAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConAviaoActionPerformed(evt);
            }
        });
        mnConsultas.add(mniConAviao);

        mniConPassageiro.setText("Passageiro");
        mniConPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConPassageiroActionPerformed(evt);
            }
        });
        mnConsultas.add(mniConPassageiro);

        mniConTripulante.setText("Tripulante");
        mniConTripulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConTripulanteActionPerformed(evt);
            }
        });
        mnConsultas.add(mniConTripulante);

        jMenuBar1.add(mnConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadVooActionPerformed
        new TelaVoo().setVisible(true);
    }//GEN-LAST:event_mniCadVooActionPerformed

    private void mniCadAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadAviaoActionPerformed
        new TelaAviao().setVisible(true);
    }//GEN-LAST:event_mniCadAviaoActionPerformed

    private void mniCadPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadPassageiroActionPerformed
        new TelaPassageiro().setVisible(true);
    }//GEN-LAST:event_mniCadPassageiroActionPerformed

    private void mniCadTripulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadTripulanteActionPerformed
        new TelaTripulante().setVisible(true);
    }//GEN-LAST:event_mniCadTripulanteActionPerformed

    private void mniConVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConVooActionPerformed
        new TelaConsulta("voo").setVisible(true);
    }//GEN-LAST:event_mniConVooActionPerformed

    private void mniConAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConAviaoActionPerformed
        new TelaConsulta("aviao").setVisible(true);
    }//GEN-LAST:event_mniConAviaoActionPerformed

    private void mniConPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConPassageiroActionPerformed
        new TelaConsulta("passageiro").setVisible(true);
    }//GEN-LAST:event_mniConPassageiroActionPerformed

    private void mniConTripulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConTripulanteActionPerformed
        new TelaConsulta("tripulante").setVisible(true);
    }//GEN-LAST:event_mniConTripulanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenuItem mniCadAviao;
    private javax.swing.JMenuItem mniCadPassageiro;
    private javax.swing.JMenuItem mniCadTripulante;
    private javax.swing.JMenuItem mniCadVoo;
    private javax.swing.JMenuItem mniConAviao;
    private javax.swing.JMenuItem mniConPassageiro;
    private javax.swing.JMenuItem mniConTripulante;
    private javax.swing.JMenuItem mniConVoo;
    // End of variables declaration//GEN-END:variables
}
